version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run:
          name: Install Required Modules
          shell: pwsh.exe
          command: |
            Install-Module -Name:('ps2exe') -Force
      - run:
          name: Build
          shell: pwsh.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build.ps1