version: 2.1
orbs:
  win: circleci/windows@2.2.0
build-and-sign-ADMU: &build-and-sign-ADMU
  - Build
  - Test Setup:
      requires:
        - Build
  - Pester Tests:
      requires:
        - Build
        - Test Setup
  - Sign Executable:
      requires:
        - Build
        - Test Setup
        - Pester Tests
  - Build Module:
      requires:
        - Build
        - Test Setup
        - Pester Tests
        - Sign Executable
  - Build Help Files:
      requires:
        - Build
        - Test Setup
        - Pester Tests
        - Sign Executable
        - Build Module
  - Build Nuspec:
      requires:
        - Build
        - Test Setup
        - Pester Tests
        - Sign Executable
        - Build Module
        - Build Help Fles
workflows:
  version: 2
  ci:
    jobs: *build-and-sign-ADMU

jobs:
  Build: # name of your job
    executor: win/default # executor type
    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run:
          name: Install Required Modules
          shell: powershell.exe
          command: |
            Install-Module -Name:('ps2exe') -Force
      - run:
          name: Build
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build.ps1
  Test Setup:
    executor: win/default
    steps:
      - run:
          name: Check directory
          command: |
            Write-Host "dir ./"
            dir ./
            Write-Host "dir ./Deploy"
            dir ./Deploy
      - run:
          name: Test Setup
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/TestSetup.ps1 -TestOrgConnectKey:($env:PesterConnectKey)
  Pester Tests:
    executor: win/default
    steps:
      - run:
          name: Invoke Pester
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./jumpcloud-ADMU/powershell/InvokePester.ps1
  Sign Executable:
    executor: win/default
    steps:
      - run:
          name: Sign .exe
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Sign.ps1 -cert_pw_key <TODO: Cert Key in secret valut>
  Build Module:
    executor: win/default
    steps:
      - run:
          name: Build Module
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build-Module.ps1
  Build Help Files:
    executor: win/default
    steps:
      - run:
          name: Build Help Files
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build-HelpFiles.ps1
  Build Nuspec:
    executor: win/default
    steps:
      - run:
          name: Build .nuspec
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/BuildNuspecFromPsd1.ps1
  

  
