version: 2.1
parameters:
  buildReleaseType:
    description: 'Semantic Version increment type of the release. Valid values: major, minor, build'
    type: string
    default: build
orbs:
  win: circleci/windows@2.2.0
build-and-sign-ADMU: &build-and-sign-ADMU
  - Build
  - Pester Tests:
      requires:
        - Build
  - Sign Executable:
      requires:
        - Build
        - Pester Tests
  - Build Module:
      requires:
        - Build
        - Pester Tests
        - Sign Executable
  - Build Help Files:
      requires:
        - Build
        - Pester Tests
        - Sign Executable
        - Build Module
  - Build Nuspec:
      requires:
        - Build
        - Pester Tests
        - Sign Executable
        - Build Module
        - Build Help Files
workflows:
  version: 2
  ci:
    jobs: *build-and-sign-ADMU

jobs:
  Build: # name of your job
    executor: win/default # executor type
    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run:
          name: Install Required Modules
          shell: powershell.exe
          command: |
            Install-Module -Name:('ps2exe') -Force
      - run:
          name: Build
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build.ps1
      - persist_to_workspace:
          root: .
          paths:
            - .
  Pester Tests:
    executor: win/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test Setup
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            . ./Deploy/TestSetup.ps1 -TestOrgConnectKey:($env:PesterConnectKey)
      - run:
          name: Install Required Modules & Set Env Variables for testing
          shell: powershell.exe
          command: |
            Install-Module -Name:('PSScriptAnalyzer') -Force
            Install-Module -Name:('JumpCloud') -Force
            If (-not [System.String]::IsNullOrEmpty($env:JCApiKey) -and -not [System.String]::IsNullOrEmpty($env:JCOrgId))
            {
                Write-Host ('[VALIDATION] JCApiKey AND JCOrgId have been populated.')
            }
            Else
            {
                Write-Error ("Unable to test because JCApiKey and JCOrgId have not been set.")
            }
      - run:
          name: Invoke Pester
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./jumpcloud-ADMU/Powershell/InvokePester.ps1
      - store_test_results:
          name: Uploading test results for ADMU'
          path: ./jumpcloud-ADMU/test_results/
  Sign Executable:
    executor: win/default
    steps:
      - run:
          name: Sign .exe
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Sign.ps1 -cert_pw_key <TODO: Cert Key in secret valut>
  Build Module:
    executor: win/default
    steps:
      - run:
          name: Build Module
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build-Module.ps1
  Build Help Files:
    executor: win/default
    steps:
      - run:
          name: Build Help Files
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build-HelpFiles.ps1
  Build Nuspec:
    executor: win/default
    steps:
      - run:
          name: Build .nuspec
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/BuildNuspecFromPsd1.ps1
  

  
