version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'
      
      - run:
          name: Build
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/Build.ps1

      - run:
          name: Test Setup
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./Deploy/TestSetup.ps1

      - run:
          name: Invoke Pester
          shell: powershell.exe
          command: |
            $ErrorActionPreference = 'Stop'
            ./jumpcloud-ADMU/powershell/InvokePester.ps1
