on: repository_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
        env:
          BASE64_ENCODED_CERT: ${{ secrets.BASE64_ENCODED_CERT }}
          CERTPASS: ${{ secrets.CERTPASS }}
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          write-host "Begin sign on branch: ${{ github.event.client_payload.branch }}"
          ./Deploy/Sign.ps1
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./jumpcloud-ADMU/Exe/gui_jcadmu.exe
          git add ./jumpcloud-ADMU/Exe/uwp_jcadmu.exe
          git add ./jumpcloud-ADMU/ADMU.cat
          git commit -m "Signed EXEs & Security Catalog"
          # TODO: return to git push after testing
          git push --dry run origin ${{ github.event.client_payload.branch }}
      - name: Draft GitHub Release and Publish
        run: |
          $user = $CIRCLECI_TOKEN
          $pass = ''
          $pair = "$($user):$($pass)"
          $encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
          $basicAuthValue = "Basic $encodedCreds"
          $Headers = @{
              Authorization = $basicAuthValue
          }
          if (${{ github.event.client_payload.branch }} -eq 'master'){
            $body = @{
                'branch'   = ${{ github.event.client_payload.branch }}
                parameters = @{
                    Publish_Release_Workflow = true
                }
            } | ConvertTo-Json
          } else {
            $body = @{
                'branch'   = ${{ github.event.client_payload.branch }}
                parameters = @{
                    Publish_CodeArtifact_Workflow = true
                }
            } | ConvertTo-Json
          }
          Invoke-WebRequest -Uri 'https://circleci.com/api/v2/project/github/TheJumpCloud/jumpcloud-ADMU/pipeline' -Headers $Headers -Body $body -Method Post
