on: repository_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
        env:
          BASE64_ENCODED_CERT: ${{ secrets.BASE64_ENCODED_CERT }}
          CERTPASS: ${{ secrets.CERTPASS }}
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          ./Deploy/Sign.ps1
          ./Deploy/Update-SecurityCatalog.ps1
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./jumpcloud-ADMU/Exe/gui_jcadmu.exe
          git add ./jumpcloud-ADMU/Exe/uwp_jcadmu.exe
          git add ./jumpcloud-ADMU/JumpCloud.ADMU.psd1
          git add ./jumpcloud-ADMU/JumpCloud.ADMU.psm1
          git add ./jumpcloud-ADMU/ADMU.cat
          git add ./jumpcloud-ADMU/PowerShell/Start-Migration.ps1
          git commit -m "Generated EXEs"
          git push
      - name: Draft GitHub Release
        run: |
          curl -u $CIRCLECI_TOKEN: -X POST \
            --header 'Content-Type: application/json' \
            -d '{
              "branch": "master",
              "parameters": {
                  "Draft_Release_Workflow" : true
              }
            }' \
          https://circleci.com/api/v2/project/github/TheJumpCloud/jumpcloud-ADMU/pipeline
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: GitHubActionTrigger
        id: publish_trigger
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
